spring.application.name=cloudcore


spring.datasource.url=jdbc:postgresql://localhost:5432/cloudcore
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=ThisIsMyVerySecretKeyForCloudCoreJwtAuthentication2026
jwt.expiration=86400000

server.port=8080